#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "🔎 Analyse du projet..."
fvm flutter analyze

echo "🚦 Vérifications avant push..."

./tools/check.sh

echo "✅ Push autorisé.">&2